# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "generic/alma8"
  config.vm.box_check_update = false
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 3500
    libvirt.memorybacking :access, :mode => "shared"
  end
  config.vm.provision "shell", inline: <<-SHELL
    set -xe
    YUM="yum -yq"
    $YUM install git rpm-build
    $YUM reinstall epel-release # epel-release is installed, but files removed
    rm -rf virtnbdbackup;
    git clone https://github.com/abbbi/virtnbdbackup
    cd virtnbdbackup
    set +x
    python3.6 setup.py bdist_rpm
    cp dist/* /vagrant
   SHELL
   config.vm.synced_folder "./", "/vagrant", type: "virtiofs"
end
